apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fintech-apis
  namespace: monitoring
spec:
  selector:
    matchLabels:
      monitoring: "true"
  namespaceSelector:
    matchNames:
    - fintech
  endpoints:
  - port: http
    path: /metrics
    interval: 30s