apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: bucket-fintech
spec:
  forProvider:
    locationConstraint: sa-east-1
    objectOwnership: BucketOwnerEnforced
  providerConfigRef:
    name: default
