apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-api
  template:
    metadata:
      labels:
        app: transaction-api
    spec:
      containers:
      - name: api
        image: transaction-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-api
  namespace: fintech
spec:
  selector:
    app: transaction-api
  ports:
  - port: 8080
    targetPort: 8080