apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: api
        image: notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: fintech
spec:
  selector:
    app: notification-service
  ports:
  - port: 8081
    targetPort: 8081