apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fintech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: api
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-connection
                  key: endpoint
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-connection
                  key: port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-connection
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-connection
                  key: password
            - name: DB_NAME
              value: "fintech"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: fintech
spec:
  selector:
    app: notification-service
  ports:
    - port: 8081
      targetPort: 8081
